import PDFDocument from "pdfkit";

// ─── Colour palette ──────────────────────────────────────────────────────────
export const GREEN = "#2d6a4f";
export const GREEN_LIGHT = "#52b788";
export const MUTED = "#6b7280";
export const TEXT = "#111827";
export const LINE = "#e5e7eb";
export const RED = "#b91c1c";

export function heading1(doc: InstanceType<typeof PDFDocument>, text: string, y?: number) {
  if (y !== undefined) doc.y = y;
  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor(TEXT)
    .text(text, 60, doc.y);
}

export function heading2(doc: InstanceType<typeof PDFDocument>, text: string) {
  doc.moveDown(1);
  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(GREEN)
    .text(text, 60);
  doc
    .moveTo(60, doc.y + 3)
    .lineTo(540, doc.y + 3)
    .strokeColor(GREEN_LIGHT)
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.5);
}

export function field(doc: InstanceType<typeof PDFDocument>, label: string, value: string | null | undefined) {
  if (!value) return;
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(MUTED)
    .text(label, 60, doc.y, { continued: true })
    .font("Helvetica")
    .fillColor(TEXT)
    .text(`  ${value}`);
}

export function twoColField(
  doc: InstanceType<typeof PDFDocument>,
  label1: string, value1: string | null | undefined,
  label2: string, value2: string | null | undefined
) {
  const y = doc.y;
  if (value1) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED).text(label1, 60, y, { width: 220, continued: true });
    doc.font("Helvetica").fillColor(TEXT).text(`  ${value1}`, { width: 220 });
  }
  if (value2) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED).text(label2, 300, y, { width: 220, continued: true });
    doc.font("Helvetica").fillColor(TEXT).text(`  ${value2}`, { width: 220 });
  }
  if (value1 || value2) doc.moveDown(0.3);
}

export function pageHeader(doc: InstanceType<typeof PDFDocument>, subtitle: string) {
  // Green bar at top
  doc.rect(0, 0, 612, 8).fill(GREEN);
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(GREEN)
    .text("WHELPWISE", 60, 20, { continued: true })
    .font("Helvetica")
    .fillColor(MUTED)
    .text(`  ·  ${subtitle}`);
  doc
    .moveTo(60, 38)
    .lineTo(540, 38)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
  doc.y = 52;
}

export function pageFooter(doc: InstanceType<typeof PDFDocument>) {
  const bottom = doc.page.height - 40;
  doc
    .moveTo(60, bottom)
    .lineTo(540, bottom)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(MUTED)
    .text(
      `Generated by WhelpWise · ${new Date().toLocaleString("en-AU", { day: "numeric", month: "long", year: "numeric", hour: "numeric", minute: "2-digit" })}`,
      60,
      bottom + 6,
      { align: "center", width: 480 }
    );
}

export function money(n: number) {
  return `$${n.toLocaleString("en-AU", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
