import { Router, type IRouter } from "express";
import PDFDocument from "pdfkit";
import {
  db,
  dogsTable,
  breedsTable,
  littersTable,
  puppiesTable,
  weightEntriesTable,
  healthTestResultsTable,
  buyersTable,
  whelpingRecordsTable,
  breedingsTable,
} from "@workspace/db";
import { eq, and } from "drizzle-orm";

const router: IRouter = Router();

// ─── Colour palette ──────────────────────────────────────────────────────────
const GREEN = "#2d6a4f";
const GREEN_LIGHT = "#52b788";
const MUTED = "#6b7280";
const TEXT = "#111827";
const LINE = "#e5e7eb";

// ─── Helpers ──────────────────────────────────────────────────────────────────
function heading1(doc: InstanceType<typeof PDFDocument>, text: string, y?: number) {
  if (y !== undefined) doc.y = y;
  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor(TEXT)
    .text(text, 60, doc.y);
}

function heading2(doc: InstanceType<typeof PDFDocument>, text: string) {
  doc.moveDown(1);
  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(GREEN)
    .text(text, 60);
  doc
    .moveTo(60, doc.y + 3)
    .lineTo(540, doc.y + 3)
    .strokeColor(GREEN_LIGHT)
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.5);
}

function field(doc: InstanceType<typeof PDFDocument>, label: string, value: string | null | undefined) {
  if (!value) return;
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(MUTED)
    .text(label, 60, doc.y, { continued: true })
    .font("Helvetica")
    .fillColor(TEXT)
    .text(`  ${value}`);
}

function twoColField(
  doc: InstanceType<typeof PDFDocument>,
  label1: string, value1: string | null | undefined,
  label2: string, value2: string | null | undefined
) {
  const y = doc.y;
  if (value1) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED).text(label1, 60, y, { width: 220, continued: true });
    doc.font("Helvetica").fillColor(TEXT).text(`  ${value1}`, { width: 220 });
  }
  if (value2) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED).text(label2, 300, y, { width: 220, continued: true });
    doc.font("Helvetica").fillColor(TEXT).text(`  ${value2}`, { width: 220 });
  }
  if (value1 || value2) doc.moveDown(0.3);
}

function pageHeader(doc: InstanceType<typeof PDFDocument>, subtitle: string) {
  // Green bar at top
  doc.rect(0, 0, 612, 8).fill(GREEN);
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(GREEN)
    .text("WHELPWISE", 60, 20, { continued: true })
    .font("Helvetica")
    .fillColor(MUTED)
    .text(`  ·  ${subtitle}`);
  doc
    .moveTo(60, 38)
    .lineTo(540, 38)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
  doc.y = 52;
}

function pageFooter(doc: InstanceType<typeof PDFDocument>) {
  const bottom = doc.page.height - 40;
  doc
    .moveTo(60, bottom)
    .lineTo(540, bottom)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(MUTED)
    .text(
      `Generated by WhelpWise · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
      60,
      bottom + 6,
      { align: "center", width: 480 }
    );
}

// ─── Litter Report ────────────────────────────────────────────────────────────
router.get("/litters/:litterId/report", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.litterId) ? req.params.litterId[0] : req.params.litterId;
  const litterId = parseInt(raw, 10);
  if (isNaN(litterId)) { res.status(400).json({ error: "Invalid litterId" }); return; }

  const [litter] = await db.select().from(littersTable).where(eq(littersTable.id, litterId));
  if (!litter) { res.status(404).json({ error: "Litter not found" }); return; }

  const [sire] = litter.sireId ? await db.select().from(dogsTable).where(eq(dogsTable.id, litter.sireId)) : [undefined];
  const [dam] = litter.damId ? await db.select().from(dogsTable).where(eq(dogsTable.id, litter.damId)) : [undefined];
  const puppies = await db.select().from(puppiesTable).where(eq(puppiesTable.litterId, litterId));
  const [whelpingRecord] = await db.select().from(whelpingRecordsTable).where(eq(whelpingRecordsTable.litterId, litterId));

  // Fetch buyer names and latest weights
  const puppyData = await Promise.all(puppies.map(async (p) => {
    const [buyer] = p.buyerId ? await db.select().from(buyersTable).where(eq(buyersTable.id, p.buyerId)) : [undefined];
    const weights = await db.select().from(weightEntriesTable).where(eq(weightEntriesTable.puppyId, p.id));
    const latestWeight = weights.length > 0 ? weights[weights.length - 1] : null;
    return { ...p, buyerName: buyer ? `${buyer.firstName} ${buyer.lastName}` : null, latestWeight };
  }));

  // ── Build PDF ──────────────────────────────────────────────────────────────
  const doc = new PDFDocument({ size: "LETTER", margins: { top: 60, bottom: 60, left: 60, right: 60 }, autoFirstPage: true });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="litter-${litterId}-report.pdf"`);
  doc.pipe(res);

  // Page 1 — Cover
  pageHeader(doc, "Litter Report");

  heading1(doc, "Litter Report", 70);
  const litterName = `${dam?.registeredName ?? "Unknown Dam"} × ${sire?.registeredName ?? "Unknown Sire"}`;
  doc
    .font("Helvetica")
    .fontSize(14)
    .fillColor(MUTED)
    .text(litterName, 60, doc.y + 4)
    .moveDown(0.5);

  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(MUTED)
    .text(`Date of Birth: ${litter.dob ? new Date(litter.dob).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }) : "TBD"}  ·  Status: ${litter.status?.toUpperCase()}`, 60);
  doc.moveDown(2);

  // Stats strip
  const stats = [
    { label: "Total Born", value: String(litter.totalBorn ?? "—") },
    { label: "Live Males", value: String(litter.liveMales ?? "—") },
    { label: "Live Females", value: String(litter.liveFemales ?? "—") },
    { label: "Stillborn", value: String(litter.stillborn ?? "0") },
  ];
  const boxW = 105;
  const boxH = 56;
  const startX = 60;
  const startY = doc.y;
  stats.forEach((s, i) => {
    const x = startX + i * (boxW + 10);
    doc.rect(x, startY, boxW, boxH).fillColor("#f0fdf4").fill();
    doc.rect(x, startY, boxW, boxH).strokeColor(GREEN_LIGHT).lineWidth(1).stroke();
    doc.font("Helvetica-Bold").fontSize(22).fillColor(GREEN).text(s.value, x, startY + 8, { width: boxW, align: "center" });
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(s.label, x, startY + 34, { width: boxW, align: "center" });
  });
  doc.y = startY + boxH + 20;

  // Dam & Sire
  heading2(doc, "Parents");
  twoColField(doc, "Dam", dam?.registeredName, "Sire", sire?.registeredName);
  twoColField(doc, "Dam Call Name", dam?.callName, "Sire Call Name", sire?.callName);
  twoColField(doc, "Dam DOB", dam?.dob ? new Date(dam.dob).toLocaleDateString("en-GB") : null, "Sire DOB", sire?.dob ? new Date(sire.dob).toLocaleDateString("en-GB") : null);
  twoColField(doc, "Dam Chip", dam?.microchip, "Sire Chip", sire?.microchip);
  twoColField(doc, "Dam Reg.", dam?.registrationNumber, "Sire Reg.", sire?.registrationNumber);

  if (whelpingRecord) {
    heading2(doc, "Whelping Details");
    twoColField(doc, "Whelping Start", whelpingRecord.startTime ?? null, "End", whelpingRecord.endTime ?? null);
    twoColField(doc, "Complications", whelpingRecord.complications ?? null, "Notes", null);
    if (whelpingRecord.complications) field(doc, "Complications", whelpingRecord.complications);
    if (whelpingRecord.notes) field(doc, "Notes", whelpingRecord.notes);
  }

  if (litter.notes) {
    heading2(doc, "Litter Notes");
    doc.font("Helvetica").fontSize(10).fillColor(TEXT).text(litter.notes, 60, doc.y, { width: 480 });
  }

  // Page 2 — Puppy Table
  doc.addPage();
  pageHeader(doc, "Litter Report — Puppy Details");
  heading1(doc, "Puppy Details");
  doc.moveDown(0.8);

  const colX = { collar: 60, sex: 130, colour: 185, birth: 270, latest: 355, status: 430 };
  const tableTop = doc.y;

  // Table header
  doc.rect(60, tableTop, 480, 20).fill("#f0fdf4");
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor(GREEN);
  doc.text("Collar", colX.collar, tableTop + 5, { width: 65 });
  doc.text("Sex", colX.sex, tableTop + 5, { width: 50 });
  doc.text("Colour", colX.colour, tableTop + 5, { width: 80 });
  doc.text("Birth Wt", colX.birth, tableTop + 5, { width: 80 });
  doc.text("Latest Wt", colX.latest, tableTop + 5, { width: 70 });
  doc.text("Buyer / Status", colX.status, tableTop + 5, { width: 100 });

  let rowY = tableTop + 22;
  puppyData.forEach((p, i) => {
    if (rowY > 680) {
      pageFooter(doc);
      doc.addPage();
      pageHeader(doc, "Litter Report — Puppy Details (cont.)");
      rowY = doc.y + 10;
    }
    if (i % 2 === 0) {
      doc.rect(60, rowY - 2, 480, 18).fill("#fafafa");
    }
    doc.font("Helvetica").fontSize(9).fillColor(TEXT);
    doc.text(p.collarColour ?? "—", colX.collar, rowY, { width: 65 });
    doc.text(p.sex ?? "—", colX.sex, rowY, { width: 50 });
    doc.text(p.colour ?? "—", colX.colour, rowY, { width: 80 });
    doc.text(p.birthWeight ? `${p.birthWeight}g` : "—", colX.birth, rowY, { width: 80 });
    doc.text(p.latestWeight ? `${p.latestWeight.weightGrams}g` : "—", colX.latest, rowY, { width: 70 });
    const buyerStatus = p.buyerName ?? (p.alive === "true" ? "Available" : "Deceased");
    doc.text(buyerStatus, colX.status, rowY, { width: 110 });
    rowY += 18;
  });

  doc.moveDown(2);

  // Weight summary per puppy
  heading2(doc, "Weight Gain Summary");
  puppyData.forEach((p) => {
    if (p.latestWeight && p.birthWeight) {
      const gain = p.latestWeight.weightGrams - p.birthWeight;
      const pct = ((gain / p.birthWeight) * 100).toFixed(1);
      const label = `${p.collarColour ?? "Pup #" + p.id} (${p.sex})`;
      twoColField(doc, label, `${p.birthWeight}g → ${p.latestWeight.weightGrams}g`, "Gain", `+${gain}g (${pct}%)`);
    }
  });

  pageFooter(doc);
  doc.end();
});

// ─── Pedigree Certificate ─────────────────────────────────────────────────────
router.get("/dogs/:dogId/pedigree-certificate", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.dogId) ? req.params.dogId[0] : req.params.dogId;
  const dogId = parseInt(raw, 10);
  if (isNaN(dogId)) { res.status(400).json({ error: "Invalid dogId" }); return; }

  const [dog] = await db.select().from(dogsTable).where(eq(dogsTable.id, dogId));
  if (!dog) { res.status(404).json({ error: "Dog not found" }); return; }

  const [breed] = dog.breedId ? await db.select().from(breedsTable).where(eq(breedsTable.id, dog.breedId)) : [undefined];
  const healthTests = await db.select().from(healthTestResultsTable).where(eq(healthTestResultsTable.dogId, dogId));

  // Build pedigree tree (3 generations)
  async function fetchAncestor(id: number | null | undefined): Promise<any> {
    if (!id) return null;
    const [d] = await db.select().from(dogsTable).where(eq(dogsTable.id, id));
    if (!d) return null;
    const [b] = d.breedId ? await db.select().from(breedsTable).where(eq(breedsTable.id, d.breedId)) : [undefined];
    return { ...d, breedName: b?.name ?? null };
  }

  const sire = await fetchAncestor(dog.sireId);
  const dam = await fetchAncestor(dog.damId);
  const sireSire = sire ? await fetchAncestor(sire.sireId) : null;
  const sireDam = sire ? await fetchAncestor(sire.damId) : null;
  const damSire = dam ? await fetchAncestor(dam.sireId) : null;
  const damDam = dam ? await fetchAncestor(dam.damId) : null;
  const ggSireSireSire = sireSire ? await fetchAncestor(sireSire.sireId) : null;
  const ggSireSireDam = sireSire ? await fetchAncestor(sireSire.damId) : null;
  const ggSireDamSire = sireDam ? await fetchAncestor(sireDam.sireId) : null;
  const ggSireDamDam = sireDam ? await fetchAncestor(sireDam.damId) : null;
  const ggDamSireSire = damSire ? await fetchAncestor(damSire.sireId) : null;
  const ggDamSireDam = damSire ? await fetchAncestor(damSire.damId) : null;
  const ggDamDamSire = damDam ? await fetchAncestor(damDam.sireId) : null;
  const ggDamDamDam = damDam ? await fetchAncestor(damDam.damId) : null;

  // ── Build PDF ──────────────────────────────────────────────────────────────
  const doc = new PDFDocument({ size: "LETTER", layout: "landscape", margins: { top: 50, bottom: 50, left: 50, right: 50 }, autoFirstPage: true });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="pedigree-${dog.registeredName.replace(/\s+/g, "-")}.pdf"`);
  doc.pipe(res);

  // Top green bar
  doc.rect(0, 0, 792, 8).fill(GREEN);

  // Header
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(GREEN)
    .text("WHELPWISE", 50, 18, { continued: true })
    .font("Helvetica")
    .fillColor(MUTED)
    .text("  ·  Pedigree Certificate");
  doc
    .moveTo(50, 36)
    .lineTo(742, 36)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();

  // Dog name + details
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(TEXT)
    .text(dog.registeredName, 50, 46);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(MUTED)
    .text(
      [
        breed?.name,
        dog.sex?.toUpperCase(),
        dog.dob ? `DOB: ${new Date(dog.dob).toLocaleDateString("en-GB")}` : null,
        dog.registrationNumber ? `Reg: ${dog.registrationNumber}` : null,
        dog.microchip ? `Chip: ${dog.microchip}` : null,
      ].filter(Boolean).join("  ·  "),
      50,
      doc.y + 2
    );
  doc.y += 4;

  doc
    .moveTo(50, doc.y + 4)
    .lineTo(742, doc.y + 4)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();

  // ── 4-generation pedigree grid ─────────────────────────────────────────────
  const pedigreeTop = doc.y + 14;
  const pageH = 612;
  const colW = [130, 150, 165, 185]; // col widths per gen
  const gutterX = 6;
  const colStart = [50, 50 + colW[0] + gutterX, 50 + colW[0] + gutterX + colW[1] + gutterX, 50 + colW[0] + gutterX + colW[1] + gutterX + colW[2] + gutterX];
  const availH = pageH - pedigreeTop - 60;

  // Ancestors: [subject], [sire, dam], [ss, sd, ds, dd], [sss, ssd, sds, sdd, dss, dsd, dds, ddd]
  const col0 = [{ ...dog, breedName: breed?.name ?? null }];
  const col1 = [sire, dam];
  const col2 = [sireSire, sireDam, damSire, damDam];
  const col3 = [ggSireSireSire, ggSireSireDam, ggSireDamSire, ggSireDamDam, ggDamSireSire, ggDamSireDam, ggDamDamSire, ggDamDamDam];

  function drawAncestorBox(doc: InstanceType<typeof PDFDocument>, ancestor: any, x: number, y: number, w: number, h: number, highlight = false) {
    const fillColor = highlight ? "#f0fdf4" : "#f9fafb";
    const borderColor = highlight ? GREEN_LIGHT : LINE;
    doc.rect(x, y, w - 4, h - 4).fillColor(fillColor).fill();
    doc.rect(x, y, w - 4, h - 4).strokeColor(borderColor).lineWidth(0.7).stroke();

    if (!ancestor) {
      doc.font("Helvetica").fontSize(7).fillColor("#d1d5db").text("Unknown", x + 4, y + (h - 4) / 2 - 4, { width: w - 12, align: "center" });
      return;
    }

    const nameLines = ancestor.registeredName.length > 22 ? 2 : 1;
    const innerY = y + 5;
    doc
      .font("Helvetica-Bold")
      .fontSize(7.5)
      .fillColor(TEXT)
      .text(ancestor.registeredName, x + 5, innerY, { width: w - 14, lineGap: 1 });
    const afterName = doc.y;
    if (ancestor.breedName) {
      doc.font("Helvetica").fontSize(6.5).fillColor(MUTED).text(ancestor.breedName, x + 5, afterName + 1, { width: w - 14 });
    }
    if (ancestor.sex) {
      const sexLabel = ancestor.sex === "male" ? "♂" : "♀";
      const sexColor = ancestor.sex === "male" ? "#3b82f6" : "#ec4899";
      doc.font("Helvetica-Bold").fontSize(7).fillColor(sexColor).text(sexLabel, x + w - 16, y + 4);
    }
    if (ancestor.registrationNumber) {
      doc.font("Helvetica").fontSize(6).fillColor(MUTED).text(ancestor.registrationNumber, x + 5, y + h - 14, { width: w - 14 });
    }
  }

  const colsData = [col0, col1, col2, col3];
  colsData.forEach((col, ci) => {
    const rowH = availH / col.length;
    col.forEach((ancestor, ri) => {
      const x = colStart[ci];
      const y = pedigreeTop + ri * rowH;
      drawAncestorBox(doc, ancestor, x, y, colW[ci], rowH, ci === 0);
    });
  });

  // ── Health Tests Section ───────────────────────────────────────────────────
  if (healthTests.length > 0) {
    const healthX = colStart[3] + colW[3] + 10;
    const healthW = 742 - healthX;
    doc
      .font("Helvetica-Bold")
      .fontSize(8.5)
      .fillColor(GREEN)
      .text("Health Test Results", healthX, pedigreeTop, { width: healthW });
    doc
      .moveTo(healthX, pedigreeTop + 14)
      .lineTo(healthX + healthW - 4, pedigreeTop + 14)
      .strokeColor(GREEN_LIGHT)
      .lineWidth(0.8)
      .stroke();

    let htY = pedigreeTop + 20;
    healthTests.forEach((t) => {
      if (htY > pageH - 80) return;
      doc.rect(healthX, htY, healthW - 4, 28).fillColor("#f0fdf4").fill();
      doc.rect(healthX, htY, healthW - 4, 28).strokeColor(LINE).lineWidth(0.5).stroke();
      doc.font("Helvetica-Bold").fontSize(7.5).fillColor(TEXT).text(t.testName, healthX + 5, htY + 4, { width: healthW - 14 });
      const resultColor = ["Clear", "Normal", "Excellent", "Good"].includes(t.result ?? "") ? "#16a34a" : "#d97706";
      doc.font("Helvetica-Bold").fontSize(8).fillColor(resultColor).text(t.result ?? "—", healthX + 5, htY + 15, { width: healthW - 14 });
      if (t.date) {
        doc.font("Helvetica").fontSize(6.5).fillColor(MUTED).text(new Date(t.date).toLocaleDateString("en-GB"), healthX + 5, htY + 15, { align: "right", width: healthW - 14 });
      }
      htY += 32;
    });
  }

  // Footer
  const bottom = pageH - 30;
  doc
    .moveTo(50, bottom)
    .lineTo(742, bottom)
    .strokeColor(LINE)
    .lineWidth(0.5)
    .stroke();
  doc
    .font("Helvetica")
    .fontSize(7.5)
    .fillColor(MUTED)
    .text(
      `Generated by WhelpWise · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })} · This certificate is produced for reference purposes.`,
      50,
      bottom + 6,
      { align: "center", width: 692 }
    );

  doc.end();
});

export default router;
